import {
  NavigationStack,
  CurrentTabScreen,
  UsersStackLayer,
} from '../../models';

export enum DispatchTypes {
  SET_CURRENT_TAB = 'SET_CURRENT_TAB',
  SET_CURRENT_VIEWABLE_POST_INDEX = 'SET_CURRENT_VIEWABLE_POST_INDEX',
  PUSH_USERS_LAYER = 'PUSH_USERS_LAYER',
  POP_USERS_LAYER = 'POP_USERS_LAYER',
  CLEAR_STACK = 'CLEAR_STACK',

  FETCH_USER_STARTED = 'FETCH_USER_STARTED',
  FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE = 'FETCH_USER_FAILURE',

  FETCH_MORE_POSTS_FROM_USER_STARTED = 'FETCH_MORE_POSTS_FROM_USER_STARTED',
  FETCH_MORE_POSTS_FROM_USER_SUCCESS = 'FETCH_MORE_POSTS_FROM_USER_SUCCESS',
  FETCH_MORE_POSTS_FROM_USER_FAILURE = 'FETCH_MORE_POSTS_FROM_USER_FAILURE',

  FOLLOW_USER_STARTED = 'FOLLOW_USER_STARTED',
  FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS',
  FOLLOW_USER_FAILURE = 'FOLLOW_USER_FAILURE',

  UNFOLLOW_USER_STARTED = 'UNFOLLOW_USER_STARTED',
  UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS',
  UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURE',
}

export interface UsersStackAction {
  type: string;
  payload: any;
}

export interface UsersStackState {
  homeTabStack: NavigationStack<UsersStackLayer>;
  userTabStack: NavigationStack<UsersStackLayer>;
  currentTab: CurrentTabScreen;
}
